# Configuration du messenger pour le développement
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # Pour le développement, on utilise le transport in-memory
            async: 'in-memory://'
            # failed: 'doctrine://default?queue_name=failed&auto_setup=0'
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            # Les emails sont traités de manière synchrone
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
