liip_imagine:
    # configure resolvers
    resolvers:
        default:
            web_path: ~

    # configure image loaders
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"
                
    # your filter sets are defined here
    filter_sets:
        # use the default cache configuration
        cache: ~
        
        # the name of the "filter set"
        thumbnail:
            quality: 80
            filters:
                # create a thumbnail: set size to 250x250 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [250, 250], mode: outbound }
                
        medium:
            quality: 85
            filters:
                thumbnail: { size: [800, 600], mode: inset } 